### ISSUE TITLE
Replace the RemoteRenderer with the VtkRenderer

### ISSUE THREAD

**Issue by Recope** [tsgouros/ParaViewWeb-SimpleDemo#4]
Do you know how to use VtkRenderer? After I replace the RemoteRenderer with the VtkRenderer, the rendering content cannot be displayed normally. Thank you in advance.

**Comment by Recope** [comment]
I instantiate the renderer as follow const renderer = VtkRenderer.newInstance({ client: model.pvwClient }); And use VtkImageDelivery on my client. Is there any additional work that needs to be done?

**Comment by Recope** [comment]
Add self.getApplication().SetImageEncoding(0) to server code will solute this problem.

**Comment by tsgouros** [comment]
Sounds solved.
